### ISSUE TITLE
undefined method `split_stylesheet_link_tag' for #<#<Class:0x007fdaa1692700>:0x007fda9f2c0d40>

### ISSUE THREAD

**Issue by bkahl** [zweilove/css_splitter#11]
I'm having an issue with trying to precompile assets for staging environment.

I'm running:

ruby 1.9.3p327
rails 3.2.13.rc2

and I've followed your steps by adding the following:
1) the css splitter gem to my GEMFILE.
2) updating the application.rb config.assets.precompile to add my newly added application_split2.css file.
**note** i didn't add the config.assets.compress = true to the applications.rb file b/c RubyMine gave me a message saying 'cannot find compress'
3) i created a new application_split2.css.scss.split2 file within the assets pipeline and made it reference the application.css.scss file by importing it like so: 
- //= include 'application.css'
  4) i added the method call '= split_stylesheet_link_tag "application", :media => "all"' within application.html.haml file in layouts directory like so:
  ---
  
  %head
    = raw analytical.head_prepend_javascript
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Projectwedding"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = favicon_link_tag
    = split_stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "print", :media => "print"
  
    = javascript_include_tag "application"
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
    = csrf_meta_tags
    = javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery?
    = raw analytical.head_append_javascript
    = dfp_helper_head
    = yield(:head)
  %body{:class=>page_class}

---

Steps followed after updating the files:
1) bundle install
2) RAILS_ENV=staging rake assets:precompile
3) restarted rails server

THEN got the following error when going to http://localhost:3000

NoMethodError in Home#index
- Showing /Users/bradkahl/RubymineProjects/projectwedding-ng/app/views/layouts/application.html.haml where line #12 raised:
- undefined method `split_stylesheet_link_tag' for #<#Class:0x007fdaa1692700:0x007fda9f2c0d40>
- 9:     %meta{:content => "", :name => "description"}
  10:     %meta{:content => "", :name => "author"}
  11:     = favicon_link_tag
  12:     = split_stylesheet_link_tag "application", :media => "all"
  13:     = stylesheet_link_tag "print", :media => "print"
  14: 
  15:     = javascript_include_tag "application"

What am I missing?

Your help is greatly appreciated!

**Comment by muskosan** [comment]
I'm running into this same issue, with the gem *outside* the assets group

**Comment by jhilden** [comment]
@muskosan can you provide some more details on used versions (gem, rails, ruby, ...), error messages, etc.?

**Comment by muskosan** [comment]
Sure, 

Error:
undefined method `split_stylesheet_link_tag' for #<#<Class:0x007fe20d023a40>:0x007fe2069c42b8>

gem v .0.4.0.
Rails 3.2.19
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]

Using the helper isn't a necessity, though it would be nice.

**Comment by jhilden** [comment]
hmm.   seems like this part is not working for you:  https://github.com/zweilove/css_splitter/blob/master/lib/css_splitter/engine.rb#L9-L13
(maybe it's not working for rails3)

you can always include the helper manually in your `ApplicationController`

**Comment by kaliara** [comment]
I found that when using Pow as my local Rack server, I had to restart it to get this error to go away.

**Comment by jefigo** [comment]
I had the same issue running on ruby 2.2.2p95 and Rails 4.2.3 application.
I had to include `helper CssSplitter::ApplicationHelper` in  the `ApplicationController` and that worked for me.

**Comment by constantm** [comment]
Thanks @jefigo, thank did the trick! For me this is caused by using the [ember-cli-rails](https://github.com/thoughtbot/ember-cli-rails) gem. When I remove the gem, it works fine.
