### ISSUE TITLE
Gem just seems to duplicate original CSS

### ISSUE THREAD

**Issue by JoeyParshley** [zweilove/css_splitter#29]
I seem to be having the issue where the gem only duplicates the original stylesheet when it creates the one that should have the excess selectors. Could someone help me troubleshoot?

**Comment by thenickcox** [comment]
@jhilden So sorry for the delay! A colleague of mine gave this a shot and apparently in the split files, the only difference from my version was that in the `*_split.css` files, he had put `= require 'application.css'`, which I thought was weird, but that worked. Would that make any sense to you?

**Comment by jhilden** [comment]
It definitely sounds weird that the file extension should have an influence on the content of your split stylesheets.  We had cases where the file extension made a different because of file loading issues with `application.css` vs. `application.js`, but doesn't sound like this is a problem in your case.

**Comment by Nuru** [comment]
I had the same problem as @thenickcox where `application_split2.css` was identical to `application.css` and solved it the same was, by changing ` *= require 'application'` to ` *= require 'application.css'` which, I suspect, gets around pulling in our `application.scss` somehow.

**Comment by jhilden** [comment]
Thanks for your report @thenickcox 

It would be really good to have a failing testcase for this exact scenario (like other test we have in https://github.com/zweilove/css_splitter/tree/master/test/dummy/app/assets/stylesheets) if anybody could contribute that.

**Comment by Nuru** [comment]
@jhilden I don't know how you'd want to set up a failing test case for this scenario. The failing case I ran into involved not having an `application.css` file at all in the project, only an `application.scss`, and the `*spit?.css` files using `*= require 'application'`. Your test cases include an `application.css` which I suspect would prevent the problem from occurring regardless of what else you added.

**Comment by jhilden** [comment]
just make a branch and change the whole setup so that it reproduces your issue.  we can worry later how to merge it back into master

**Comment by markedmondson** [comment]
I'm having this same problem and even switching the `_splitN.css` files to `require 'application.css'` instead of just `require 'application'` doesn't seem to be helping. 

Any further suggestions?
