### ISSUE TITLE
Issue with Key frames

### ISSUE THREAD

**Issue by rohitagarwal** [zweilove/css_splitter#38]
This is what happening when using css_splitter

**Original:**
*@-ms-keyframes rotate-spinner {
  0% {
    -moz-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    -ms-transform: rotate(0deg);
    transform: rotate(0deg);
    zoom: 1;
  }
  100% {
    -moz-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    -ms-transform: rotate(360deg);
    transform: rotate(360deg);
    zoom: 1;
  }
}*

**Original Split 1:** 
*@-ms-keyframes rotate-spinner {
  0% {
    -moz-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    -ms-transform: rotate(0deg);
    transform: rotate(0deg);
    zoom: 1;
  }*

**Original Split 2:**
*100% {
    -moz-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    -ms-transform: rotate(360deg);
    transform: rotate(360deg);
    zoom: 1;
  }
}*

Is there a way to fix it?

**Comment by KurtPreston** [comment]
Seems like this is still an issue, but wanted to echo @larrybotha that an easy work-around is to re-order your CSS partials.

**Comment by larrybotha** [comment]
ye, that's exactly what I did, @KurtPreston :)

**Comment by danielhusar** [comment]
I have same issue with keyframes. (reordering of course fixes that)

**Comment by jhilden** [comment]
contributions in form of a failing test case or a pull request are very welcome.  I don't think I will be able to tackle this in the forseeable future.

**Comment by rubenswieringa** [comment]
We came across this problem as well and made fix: [**Pull-request**](https://github.com/zweilove/css_splitter/pull/55) ([fork](https://github.com/nedap/css_splitter/tree/prevent-keyframes-split))

**Comment by jhilden** [comment]
should be fixed with version `0.4.2`
