### ISSUE TITLE
fail to precompile

### ISSUE THREAD

**Issue by shi02022211** [zweilove/css_splitter#46]
can someone please help?

I have a /app/assets/stylesheets/themes/default/app.css.scss.
so I created /app/assets/stylesheets/themes/default/app_split2.css in the same directory

i included these lines in app_split2.css
# app/assets/stylesheets/themes/default/app_split2.css

```css
/*
 *= require 'app'
 */
```

in development.rb I added

```ruby
config.assets.precompile += %w(
    themes/*/public.css
    themes/*/public.js
    themes/*/app.css
    themes/*/app_split2.css
    themes/*/app.js
    themes/default/sprites.css
  )
```

but when precomplie, i got this error :

```
couldn't find file 'app'
  (in /home/appcara/projects/portal-cosn/app/assets/stylesheets/themes/default/app_split2.css:4)
```

did i do anything wrong?

**Comment by jhilden** [comment]
@shi02022211 does your issue still persist?  Do you have any additional information for us?

**Comment by jhilden** [comment]
closing this for now due to inactivity
