### ISSUE TITLE
Single rule with > 4095 selectors not split

### ISSUE THREAD

**Issue by Nuru** [zweilove/css_splitter#56]
By using too many libraries, we ended up with the CSS rule `{float: right; }` having over 5,000 selectors attached to it. `css_splitter` did put that one rule alone in a file, but it's still too many selectors for IE 9. It needs to take a rule like that and split it into 2 rules.

**Comment by jhilden** [comment]
I'm sorry, but I think I would rather not want to support this edge case.  You are clearly writing suboptimal code there and I would rather not encourage something like that.

If someboy else writes a really good PR with good test coverage for it, I might reconsider, but I will definitely not write any code myself.  I'm sorry, I hope you understand my reasoning.

**Comment by Nuru** [comment]
I totally agree this is sub-optimal code (facilitated in our case by the combination of SASS and Foundation and Compass and a few other CSS frameworks) and I understand your lack of interest in wasting resources supporting it. Still, it would be nice if 

- This were listed as a known limitation
- A warning message was output when this condition arises

Otherwise, `css_splitter` appears to work but hard-to-detect and harder-to-debug formatting errors show up in IE 9. 

As for us, with some careful cleanup and refactoring, we got the whole project under 4096 selectors and got rid of `css_splitter` altogether.

**Comment by jhilden** [comment]
I would gladly merge a PR that mentions the limitation in the README or outputs a warning during compilation.

> Otherwise, css_splitter appears to work but hard-to-detect and harder-to-debug formatting errors show up in IE 9.

If there are any serious issues with IE9 caused by this gem, we would certainly love to hear about them.

> As for us, with some careful cleanup and refactoring, we got the whole project under 4096 selectors and got rid of css_splitter altogether.

That's really good to hear.  I also try not to use `css_splitter` whereever possible.
