### ISSUE TITLE
Rails 3 sprockets engine issue

### ISSUE THREAD

**Issue by fatbeard2** [zweilove/css_splitter#67]
Hi. This commit https://github.com/zweilove/css_splitter/commit/c5e37a8141c628a9eaddb55bfce5b96cb615f191 introduced a regression. For rails 3.2 and sprockets 2.2.3 `assets.register_bundle_processor` is never called. So the engine is not registered.

**Comment by jhilden** [comment]
thanks for the report @fatbeard2 

would you mind submitting a PR that will work for both rails 3.2 (sprockets 2.x) and 4.2.5 (sprockets 3.x)?

**Comment by fatbeard2** [comment]
Sure I'll take a look at it soon

**Comment by fatbeard2** [comment]
Btw, I thought(by looking at history) that this repo had a CI build set up to run against rails 3 and rails 4?
