### ISSUE TITLE
Sprockets v3.7.0 deprecations

### ISSUE THREAD

**Issue by adzap** [zweilove/css_splitter#69]
Hi. Seems sprockets 3.7.0 contains the deprecations for v4. I am getting the following message

> DEPRECATION WARNING: You are using the a deprecated processor interface CssSplitter::SprocketsEngine.
> remote:        Please update your processor interface:
> remote:        https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors

The document mentioned outlines ways to support versions 2,3,4 or just 3 and 4, going forward.

Let me know if you would like some assistance.

**Comment by bhalash** [comment]
I'm hitting this too and happy to help out with a PR!

**Comment by jhilden** [comment]
Since I'm not really actively developing new features for this gem (see: https://github.com/zweilove/css_splitter#development-status) any assitence/PR would be very welcome indeed.

Let me know if I can help with anything.

**Comment by bhalash** [comment]
@jhilden Grand! I'll take a poke at this later and get it updated for Rails 4/5. Curse my company for requiring IE8 support!

**Comment by nahankid** [comment]
@bhalash, any luck with this? Please let me know if I can help.

**Comment by pabois** [comment]
Hi, any news?

Thanks

**Comment by jhilden** [comment]
@pabois @nahankid #70 has been merged and version `0.4.6` has been released.

Please reopen, if there should be any remaining issues with this.

**Comment by pabois** [comment]
Great, ty!
